- name: PLAY-1
  hosts: localhost
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "hello from play1 and task1"

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: play2 and task2
    ansible.builtin.debug:
      msg: "hello from play2 and task2"   #### debug is used for printing msg