- name: using shell commands in ansible
  hosts: localhost
  tasks:
  - name: checking roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user

  - name: print the user
    ansible.builtin.debug: 
      msg: the output of user is {{user}} 
