- name: using shell commands in ansible
  hosts: localhost
  tasks:
  - name: checking roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: print the user
    ansible.builtin.debug: 
      msg: the output of user is {{user}} 

  - name: print the status
    ansible.builtin.debug:
      msg: the status of user is {user.rc}}

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0      


