- name: using shell commands in ansible
  hosts: localhost
  tasks:
  - name: using a shell command
    ansible.builtin.command: ps -ef
    register: output
    
  - name: output of  shell command
    ansible.builtin.debug: 
      msg: "the msg is {{output}}"
