- name: multiple packages install in ansible
  hosts: localhost
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - maven
      