- name: multiple packages install in ansible
  hosts: localhost
  become: yes
  tasks:
  # - name: install the packages
  #   ansible.builtin.package:
  #     name: "{{item}}"
  #     state: present
  #   loop:
  #   - git
  #   - maven

    - name: install the packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name:'git', state:'present' }
    - { name:'maven', state:'present' }
    
      